AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ChimeSDKCalling
  
  Sample SAM Template for ChimeSDKCalling

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"
  Function:
    Timeout: 30
    MemorySize: 128
    Runtime: nodejs20.x
    Architectures:
      - x86_64
    Environment:
      Variables:
        NODE_ENV: production

Resources:
  ChimeSDKFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/chime-sdk/
      Handler: app.lambdaHandler
      Events:
        CreateMeeting:
          Type: Api
          Properties:
            Path: /create-meeting
            Method: post
        AddAttendee:
          Type: Api
          Properties:
            Path: /add-attendee
            Method: post
        GetMeeting:
          Type: Api
          Properties:
            Path: /get-meeting
            Method: get
        ListAttendees:
          Type: Api
          Properties:
            Path: /list-attendees
            Method: get
        DeleteAttendee:
          Type: Api
          Properties:
            Path: /delete-attendee
            Method: post
        DeleteMeeting:
          Type: Api
          Properties:
            Path: /delete-meeting
            Method: post
        StartTranscription:
          Type: Api
          Properties:
            Path: /start-meeting-transcription
            Method: post
        StopTranscription:
          Type: Api
          Properties:
            Path: /stop-meeting-transcription
            Method: post
      Description: Chime SDK Lambda Function

Outputs:
  ChimeSDKApi:
    Description: "API Gateway endpoint URL for Prod stage for Chime SDK function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/chime/"
  ChimeSDKFunction:
    Description: "Chime SDK Lambda Function ARN"
    Value: !GetAtt ChimeSDKFunction.Arn
  ChimeSDKFunctionIamRole:
    Description: "Implicit IAM Role created for Chime SDK function"
    Value: !GetAtt ChimeSDKFunctionRole.Arn
